name: graphql_repro
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphql: ^5.0.0-nullsafety.3
  json_serializable: ^4.1.0
  artemis: ^7.0.0-beta.3

#  needed to create dart files
#  build_runner: ^1.7.2
#  json_serializable: ^3.2.3
#  artemis: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

